---
title: "[JavaScript] Promise, 프로미스"
excerpt: "JavaScript 비동기 처리를 도와주는 프로미스에 대해 알아보자."

categories:
    - development
tags:
    - JavaScript
    - js
    - asynchronous
    - Promise
---
![promise](/assets/images/promise.jpg)

> 해당 글은 유튜버 '드림코딩 엘리'님의 영상을 참조하여 공부하면서 작성하였습니다.


# JavaScript Promise
프로미스는 비동기 처리를 위한 자바스크립트의 오브젝트이다.
들어가기 전에 간단하게 알고 넘어갈 것들이 있는데 그 중 하나는 State에 대한 것이다. `Promise`의 상태에는 대기 상태인 `pending`과 완료 `fulfilled`, 실패 `rejected`가 있다.
또 다른 하나는 `Producer`와 `Consumers`으로 나눠진다는 것이다.

## Producer

`Producer`는 아래와 같이 만들 수 있다.

```js
const promise = new Promise((resolve, reject) => {
    // doing some heavy work (network, read files etc)
    console.log('doing something..');
    setTimeout(() => resolve('finish'), 1000);
});
```
`Promise` 객체는 만들어지는 순간 안에 콜백함수로 주어지는 `executor`가 자동으로 실행된다. 즉 `Promise` 안에 네트워크 요청을 하는 코드가 있다고 하면 `executor`로 불리는 콜백함수가 바로 요청을 보내게 된다. 사용자가 버튼을 눌렀을 때 네트워크 요청을 보내야하는 경우라면 이 경우에 불필요한 네트워크 통신을 한다는 것인데 이 점을 염두하고 코드를 작성하면 좋을 것이다.

## Consumers

`Producer`를 만들었으면 이를 사용하는 `Consumers`도 만들어보자. `Consumers`가 제공하는 API는 `then`, `catch`, `finally`가 있다.

### then

`then`을 이용하면 성공적으로 값이 `resolve`의 인자로 들어온다면 실행된다.

```js
promise.then(value => {
    console.log(value);
});
// doing something..
// finish (after 1 sec)
```

## catch

`catch`는 무언가 실패하면 `error`를 전달하는 `reject`에 의해 실행된다. `Producer`에서 에러 객체를 전달해보자.

```js
const promise = new Promise((resolve, reject) => {
    // doing some heavy work (network, read files etc)
    console.log('doing something..');
    setTimeout(() => reject(new Error('No network.')), 1000);
});

promise
.then(value => console.log(value))
.catch(error => console.log(error));
// doing something..
// No network. (after 1 sec)
```

`Promise`에서는 Chaining을 걸 수 있기 때문에 위와 같이 `then`에서 리턴된 값이 `catch`로 들어오게 된다.

## finally

`finally`는 성공하든 실패하든 무조건 마지막에 호출된다. 

```js
promise
.then(value => console.log(value))
.catch(error => console.log(error))
.finally(() => console.log('finally'));

// doing something..
// finish or No network. (after 1 sec)
// finally
```

## Chaining & Error handling

재미있는 예제를 다뤄보자. 아래에는 `shortcut`을 활용했는데 리턴된 값과 함수에 들어가는 인자가 같다면 아래와 같이 줄여서 쓸 수 있다.

```js
promise
.then(value => console.log(value))
.catch(error => console.log(error))
.finally(() => console.log('finally'));

// shortcut
promise
.then(console.log)
.catch(console.log)
.finally(() => console.log('finally'));
```

예제를 살펴보자. 아래 예제는 Chining을 활용하여 닭을 만들고, 1초 뒤에 계란을 낳고, 1초 뒤에 후라이를 만드는 예제이다. 에러가 발생하면 앞에서 만들어진 포맷팅을 무시하고 `catch`를 통해 새로운 값을 리턴하여 어떻게든 계란후라이를 만들어낸다.

```js
const getHen = () => 
	new Promise((resolve, reject) => {
		setTimeout(() => resolve('🐓'), 1000);
	});

let getEgg = hen =>
	new Promise((resolve, reject) => {
		setTimeout(() => resolve(`${hen} => 🥚`), 1000);
	});

const cook = egg =>
	new Promise((resolve, reject) => {
		setTimeout(() => resolve(`${egg} => 🍳`), 1000);
	});
// Chaining
getHen()
.then(getEgg)
.then(cook)
.then(console.log); // 🐓 => 🥚 => 🍳

getEgg = hen =>
	new Promise((resolve, reject) => {
		// throw error
		setTimeout(() => reject(new Error(`error! ${hen} => 🥚`)), 1000);
	});

// Error handling
getHen()
.then(getEgg)
.then(cook)
.then(console.log)
.catch(console.log); // Error: error! 🐓 => 🥚

getHen()
.then(getEgg)
.catch(error => '🏪 (buy egg)') // Catch
.then(cook)
.then(console.log); // 🏪 (buy egg) => 🍳
```

## 마치며
원래 어느정도 알고 사용해본 경험이 있었지만 간결한 설명과 재미있는 예제를 통해 기존에 알고 있던 지식보다도 좀 더 배울 수 있었다. 필자의 글로 이해하기 어렵다면 아래 링크된 주소로 들어가 영상을 시청하면 충분히 이해를 도울 수 있을 것이다.

https://www.youtube.com/watch?v=JB_yU6Oe2eE&t=1321s
